<?php

namespace MyFrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * tRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tRepository extends EntityRepository
{
}
