my_frontend_contact:
    resource: "@FrontSupportBundle/Controller/ContactController.php"
    type:     annotation

my_frontend_story:
    resource: "@FrontSupportBundle/Controller/StoryController.php"
    type:     annotation

my_frontend_carousel:
    resource: "@FrontSupportBundle/Controller/CarouselController.php"
    type:     annotation

my_frontend_squad:
    resource: "@FrontSupportBundle/Controller/SquadController.php"
    type:     annotation

my_frontend_album:
    resource: "@FrontSupportBundle/Controller/AlbumController.php"
    type:     annotation

my_frontend_album:
    resource: "@FrontSupportBundle/Controller/AlbumController.php"
    type:     annotation

my_frontend_album:
    resource: "@FrontSupportBundle/Controller/AlbumController.php"
    type:     annotation

my_frontend_album:
    resource: "@FrontSupportBundle/Controller/AlbumController.php"
    type:     annotation

my_frontend_image:
    resource: "@FrontSupportBundle/Controller/ImageController.php"
    type:     annotation

my_frontend_image:
    resource: "@FrontSupportBundle/Controller/ImageController.php"
    type:     annotation

my_frontend_tasks:
    resource: "@FrontSupportBundle/Controller/TasksController.php"
    type:     annotation

my_frontend_tasks:
    resource: "@FrontSupportBundle/Controller/TasksController.php"
    type:     annotation

my_user:
    resource: "@MyUserBundle/Controller/"
    type:     annotation
    prefix:   /user

my_frontend:
    resource: "@FrontSupportBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
