<?php

namespace FrontSupportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SquadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SquadRepository extends EntityRepository
{
}
