_homepage:
    pattern: /
    defaults: { _controller: MyFrontendBundle:Default:index }

#my_frontend:
#    resource: "@MyFrontendBundle/Controller/"
#    type:     annotation
#    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
